/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.12/userguide/multi_project_builds.html in the Gradle documentation.
 */
rootProject.name = "2024-12-otus-java-elistratov"
include("hw01-gradle")
include("hw02-generics")
include("hw03-annotations")
include("hw04-gc")
include("hw05-autologging")
include ("hw06-ATM")

pluginManagement {
    val foojayResolverConvention: String by settings
    val dependencyManagement: String by settings
    val johnrengelmanShadow: String by settings
    val springframeworkBoot: String by settings
    val protobufVer: String by settings
    val spotless: String by settings
    val jgitver: String by settings
    val sonarlint: String by settings

    plugins {
        // Apply the foojay-resolver plugin to allow automatic download of JDKs
        id("org.gradle.toolchains.foojay-resolver-convention") version foojayResolverConvention
        id("com.github.johnrengelman.shadow") version johnrengelmanShadow
        id("io.spring.dependency-management") version dependencyManagement
        id("org.springframework.boot") version springframeworkBoot
        id("com.google.protobuf") version protobufVer
        id("com.diffplug.spotless") version spotless
        id("fr.brouillard.oss.gradle.jgitver") version jgitver
        id("name.remal.sonarlint") version sonarlint

    }
}

